name: Daily Weather Data Ingestion

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch: 

jobs:
  run-pipeline:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run ETL Script
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python weather_pipeline.py
