steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install Libraries
    run: pip install -r requirements.txt

  - name: Run ETL Script
    env:
      # This pulls the secret from your GitHub vault and passes it to Python
      AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
    run: python weather_pipeline.py
